### ISSUE TITLE
Decode math issue?

### ISSUE THREAD

**Issue by mbl** [sentharn/encode-normals#1]
In the tutorial you say each normal is encoded by dividing by two, then adding 0.5.

This turns -1..1 to 0..1 range. 

For decoding you suggest multiplying by 2, then subtracting 0.5.

That would turn 0..1 into -0.5 .. 1.5 range.

I might be missing something, but I think your resulting normals would be off, so you want to subtract a full 1 when decoding..

**Comment by sentharn** [comment]
I think it works properly? Visually, at least. Check out this comparison of the normals visually, by connecting them directly to shader output.

![math1](https://user-images.githubusercontent.com/74167590/178307267-2784b2fb-b7ea-456f-be0b-4ebd6bb22333.JPG)

Subtracting 1 yields a normal that is "too dark" and doesn't match the other two.

However, math wise, your solution is correct, so I'm not sure what's going on. In fact, I think the proper operation is actually subtract first, then multiply, but that doesn't work either...

**Comment by mbl** [comment]
Okay I retract this issue. There is some other factor here that I am not aware of, important thing is that it works!

**Comment by sentharn** [comment]
converting the transformed normal via `color = Vector(Color(color).from_scene_linear_to_srgb())` seems to work.

**Comment by sentharn** [comment]
Bobbe on the Blender Community Discord pointed me towards color space conversion (I think the shader editor only understands sRGB, and normals are...not stored in sRGB). 

Here's original normals, vs updated script using sRGB and subtracting 1, vs old script subtracting 0.5 and 0.1, respectively. 

I'll update the release later today. thank you so much for reporting this!

![issue1_normals](https://user-images.githubusercontent.com/74167590/178324200-3dd70363-9d37-4412-9211-8bd144b63835.png)

![issue1_newscript_1 0](https://user-images.githubusercontent.com/74167590/178324256-8e37af29-d0ff-47c7-a749-c4507d93f7ff.png)

![issue1_oldscript_0 5](https://user-images.githubusercontent.com/74167590/178324230-fbb833cc-a02f-4c61-95c3-13802be96541.png)

![issue1_oldscript_1 0](https://user-images.githubusercontent.com/74167590/178324464-bdcf348a-9b25-422c-aa3d-a34b7583e1cb.png)
